require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.1
  NewCops: enable
  Exclude:
    # - services/**/*
    - vendor/**/*
    # - db/**/*
    - bin/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
