default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV['DB_PORT'] { 5432 } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV["DB_PASSWORD"] { "password" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
development:
  <<: *default
  database: data_processing_app_development
test:
  <<: *default
  database: data_processing_app_test
production:
  <<: *default
  database: data_processing_app_production